//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pegatron.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pegatron.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap backarrow {
            get {
                object obj = ResourceManager.GetObject("backarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap BGService {
            get {
                object obj = ResourceManager.GetObject("BGService", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap CalDUTSA {
            get {
                object obj = ResourceManager.GetObject("CalDUTSA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 SGDUT
        ///HAS_REF,REF_DATE
        ///FALSE,
        ///FREQ,Port1A,Port1B,Port2A,Port2B,Port3A,Port3B,Port4A,Port4B
        ///,,,,,,,,
        ///SADUT
        ///HAS_REF,REF_DATE
        ///FALSE,
        ///FREQ,Port1A,Port1B,Port2A,Port2B,Port3A,Port3B,Port4A,Port4B
        ///,,,,,,,, 的當地語系化字串。
        /// </summary>
        internal static string CalibrationData {
            get {
                return ResourceManager.GetString("CalibrationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap CalSGDUT {
            get {
                object obj = ResourceManager.GetObject("CalSGDUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap enlarge_icon_small {
            get {
                object obj = ResourceManager.GetObject("enlarge-icon-small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap imageIconBtn {
            get {
                object obj = ResourceManager.GetObject("imageIconBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap InstrumentSetup {
            get {
                object obj = ResourceManager.GetObject("InstrumentSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loadanimation {
            get {
                object obj = ResourceManager.GetObject("loadanimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap refresh_2_24 {
            get {
                object obj = ResourceManager.GetObject("refresh-2-24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 DUT,192.168.100.254,,(IQxstream-M),,,
        ///SMB100A,192.168.100.2,,,,,
        ///FPL1007,192.168.100.3,,,,,
        ///2-1 Switch,192.168.100.251,,,,,
        ///Power Sensor,USB0::0x0AAD::0x00E2::114435::INSTR,,,,,
        ///1. VSG Power Accuracy,,,,,,
        ///High Power Accuracy,,,,,,
        ///RF1 B1,1,,,,,
        ///RF1 B2,0,,,,,
        ///RF2 B1,0,,,,,
        ///RF2 B2,0,,,,,
        ///RF3 B1,0,,,,,
        ///RF3 B2,0,,,,,
        ///RF4 B1,0,,,,,
        ///RF4 B2,0,,,,,
        ///Power(dBm),-10,5,,,,
        ///Frequency(MHz),860,1770,2000,3300,4900,5800
        ///Acceptance Limit (dBï¿½),,,,,,
        ///400-3800 MHz,0.5,,,,,
        ///3801-7300 Mhz,1,,,,,
        ///,,,,,,
        ///L [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Specifications_IQxstream_M {
            get {
                return ResourceManager.GetString("Specifications_IQxstream_M", resourceCulture);
            }
        }
    }
}
